#######################################################################
#+-------------------------------------------------------------------+#
#|                                                                   |#  
#|                      SuffixesPlus Configuration                   |#
#|                            By dmulloy2                            |#
#|                                                                   |#
#+-------------------------------------------------------------------+#
#######################################################################

# Maximum lengths
maxLengths:
  prefix: 10
  suffix: 10

# Commands
# %p is replaced with the player's name
# %s with the new suffix
commands:
  prefix: 'manuaddv %p prefix %s'
  prefixReset: 'manudelv %p prefix'
  suffix: 'manuaddv %p suffix %s'
  suffixReset: 'manudelv %p suffix'