name: SuffixesPlus
main: net.dmulloy2.suffixesplus.SuffixesPlus
version: 3.0.1
author: dmulloy2
description: Allows players to set their own prefix or suffix if they have the correct permissions
commands:
  prefix:
    description: Sets your prefix
    usage: /<command> <args>
    aliases: [pre]
  suffix:
    description: Sets your suffix
    usage: /<command> <args>
    aliases: [suf]
  prefixreset:
    description: Reset a player's prefix
    usage: /<command> <player>
    aliases: [prer]
  suffixreset:
    description: Reset a player's suffix
    usage: /<command> <player>
    aliases: [sufr]
  suffixesplus:
    description: SuffixesPlus root command
    usage: /<command>
  listen:
    description: Listen to another player
    usage: /<command> <player>
    aliases: [listento]
  listening:
    description: List players you are listening to
    usage: /<command>
    aliases: [listeningto]
permissions:
  sp.admin:
    description: Allows access to commands meant for Admins
    children:
      sp.reload: true
      sp.moderator: true
      sp.highroller: true
  sp.moderator:
    description: Allows access to prefix and suffix reset
    children:
      sp.prefix.reset: true
      sp.prefix.reset.others: true
      sp.suffix.reset: true
      sp.suffix.reset.others: true
  sp.highroller:
    description: Allows access to suffix and prefix
    children:
      sp.prefix: true
      sp.suffix: true
  sp.prefix:
    default: false
  sp.prefix.others:
    default: false
  sp.prefix.reset:
    default: false
  sp.prefix.reset.others:
    default: false
  sp.suffix:
    default: false
  sp.suffix.others:
    default: false
  sp.suffix.reset:
    default: false
  sp.suffix.reset.others:
    default: false
  sp.reload:
    default: false